/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.weathersnapshot.db;


import com.kbalazsworks.weathersnapshot.db.tables.FlywaySchemaHistory;
import com.kbalazsworks.weathersnapshot.db.tables.HtmlLogs;
import com.kbalazsworks.weathersnapshot.db.tables.ParsedTemperatureSnapshots;
import com.kbalazsworks.weathersnapshot.db.tables.SiteUris;
import com.kbalazsworks.weathersnapshot.db.tables.Sites;
import com.kbalazsworks.weathersnapshot.db.tables.records.FlywaySchemaHistoryRecord;
import com.kbalazsworks.weathersnapshot.db.tables.records.HtmlLogsRecord;
import com.kbalazsworks.weathersnapshot.db.tables.records.ParsedTemperatureSnapshotsRecord;
import com.kbalazsworks.weathersnapshot.db.tables.records.SiteUrisRecord;
import com.kbalazsworks.weathersnapshot.db.tables.records.SitesRecord;

import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<HtmlLogsRecord, Long> IDENTITY_HTML_LOGS = Identities0.IDENTITY_HTML_LOGS;
    public static final Identity<ParsedTemperatureSnapshotsRecord, Long> IDENTITY_PARSED_TEMPERATURE_SNAPSHOTS = Identities0.IDENTITY_PARSED_TEMPERATURE_SNAPSHOTS;
    public static final Identity<SiteUrisRecord, Integer> IDENTITY_SITE_URIS = Identities0.IDENTITY_SITE_URIS;
    public static final Identity<SitesRecord, Integer> IDENTITY_SITES = Identities0.IDENTITY_SITES;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = UniqueKeys0.FLYWAY_SCHEMA_HISTORY_PK;
    public static final UniqueKey<HtmlLogsRecord> HTML_LOGS_PKEY = UniqueKeys0.HTML_LOGS_PKEY;
    public static final UniqueKey<ParsedTemperatureSnapshotsRecord> PARSED_TEMPERATURE_SNAPSHOTS_PKEY = UniqueKeys0.PARSED_TEMPERATURE_SNAPSHOTS_PKEY;
    public static final UniqueKey<SiteUrisRecord> SITE_URIS_PKEY = UniqueKeys0.SITE_URIS_PKEY;
    public static final UniqueKey<SitesRecord> SITES_PKEY = UniqueKeys0.SITES_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<HtmlLogsRecord, Long> IDENTITY_HTML_LOGS = Internal.createIdentity(HtmlLogs.HTML_LOGS, HtmlLogs.HTML_LOGS.ID);
        public static Identity<ParsedTemperatureSnapshotsRecord, Long> IDENTITY_PARSED_TEMPERATURE_SNAPSHOTS = Internal.createIdentity(ParsedTemperatureSnapshots.PARSED_TEMPERATURE_SNAPSHOTS, ParsedTemperatureSnapshots.PARSED_TEMPERATURE_SNAPSHOTS.ID);
        public static Identity<SiteUrisRecord, Integer> IDENTITY_SITE_URIS = Internal.createIdentity(SiteUris.SITE_URIS, SiteUris.SITE_URIS.ID);
        public static Identity<SitesRecord, Integer> IDENTITY_SITES = Internal.createIdentity(Sites.SITES, Sites.SITES.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, "flyway_schema_history_pk", new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
        public static final UniqueKey<HtmlLogsRecord> HTML_LOGS_PKEY = Internal.createUniqueKey(HtmlLogs.HTML_LOGS, "html_logs_pkey", new TableField[] { HtmlLogs.HTML_LOGS.ID }, true);
        public static final UniqueKey<ParsedTemperatureSnapshotsRecord> PARSED_TEMPERATURE_SNAPSHOTS_PKEY = Internal.createUniqueKey(ParsedTemperatureSnapshots.PARSED_TEMPERATURE_SNAPSHOTS, "parsed_temperature_snapshots_pkey", new TableField[] { ParsedTemperatureSnapshots.PARSED_TEMPERATURE_SNAPSHOTS.ID }, true);
        public static final UniqueKey<SiteUrisRecord> SITE_URIS_PKEY = Internal.createUniqueKey(SiteUris.SITE_URIS, "site_uris_pkey", new TableField[] { SiteUris.SITE_URIS.ID }, true);
        public static final UniqueKey<SitesRecord> SITES_PKEY = Internal.createUniqueKey(Sites.SITES, "sites_pkey", new TableField[] { Sites.SITES.ID }, true);
    }
}
