/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.weathersnapshot.db;


import com.kbalazsworks.weathersnapshot.db.tables.FlywaySchemaHistory;
import com.kbalazsworks.weathersnapshot.db.tables.HtmlLogs;
import com.kbalazsworks.weathersnapshot.db.tables.ParsedTemperatureSnapshots;
import com.kbalazsworks.weathersnapshot.db.tables.SiteUris;
import com.kbalazsworks.weathersnapshot.db.tables.Sites;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -594907488;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.html_logs</code>.
     */
    public final HtmlLogs HTML_LOGS = HtmlLogs.HTML_LOGS;

    /**
     * The table <code>public.parsed_temperature_snapshots</code>.
     */
    public final ParsedTemperatureSnapshots PARSED_TEMPERATURE_SNAPSHOTS = ParsedTemperatureSnapshots.PARSED_TEMPERATURE_SNAPSHOTS;

    /**
     * The table <code>public.site_uris</code>.
     */
    public final SiteUris SITE_URIS = SiteUris.SITE_URIS;

    /**
     * The table <code>public.sites</code>.
     */
    public final Sites SITES = Sites.SITES;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.HTML_LOGS_ID_SEQ,
            Sequences.PARSED_TEMPERATURE_SNAPSHOTS_ID_SEQ,
            Sequences.SITE_URIS_ID_SEQ,
            Sequences.SITES_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            HtmlLogs.HTML_LOGS,
            ParsedTemperatureSnapshots.PARSED_TEMPERATURE_SNAPSHOTS,
            SiteUris.SITE_URIS,
            Sites.SITES);
    }
}
