/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.weathersnapshot.db;


import org.jooq.Sequence;
import org.jooq.impl.Internal;


/**
 * Convenience access to all sequences in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.html_logs_id_seq</code>
     */
    public static final Sequence<Long> HTML_LOGS_ID_SEQ = Internal.createSequence("html_logs_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.parsed_temperature_snapshots_id_seq</code>
     */
    public static final Sequence<Long> PARSED_TEMPERATURE_SNAPSHOTS_ID_SEQ = Internal.createSequence("parsed_temperature_snapshots_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.site_uris_id_seq</code>
     */
    public static final Sequence<Integer> SITE_URIS_ID_SEQ = Internal.createSequence("site_uris_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.sites_id_seq</code>
     */
    public static final Sequence<Integer> SITES_ID_SEQ = Internal.createSequence("sites_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
