/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.weathersnapshot.db.tables.records;


import com.kbalazsworks.weathersnapshot.db.tables.HtmlLogs;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HtmlLogsRecord extends UpdatableRecordImpl<HtmlLogsRecord> implements Record7<Long, Integer, Integer, Integer, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -835650761;

    /**
     * Setter for <code>public.html_logs.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.html_logs.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.html_logs.site_id</code>.
     */
    public void setSiteId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.html_logs.site_id</code>.
     */
    public Integer getSiteId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.html_logs.site_uri_id</code>.
     */
    public void setSiteUriId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.html_logs.site_uri_id</code>.
     */
    public Integer getSiteUriId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.html_logs.parser_version_id</code>.
     */
    public void setParserVersionId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.html_logs.parser_version_id</code>.
     */
    public Integer getParserVersionId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.html_logs.html</code>.
     */
    public void setHtml(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.html_logs.html</code>.
     */
    public String getHtml() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.html_logs.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.html_logs.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.html_logs.parsed</code>.
     */
    public void setParsed(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.html_logs.parsed</code>.
     */
    public LocalDateTime getParsed() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Integer, Integer, Integer, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, Integer, Integer, Integer, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return HtmlLogs.HTML_LOGS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return HtmlLogs.HTML_LOGS.SITE_ID;
    }

    @Override
    public Field<Integer> field3() {
        return HtmlLogs.HTML_LOGS.SITE_URI_ID;
    }

    @Override
    public Field<Integer> field4() {
        return HtmlLogs.HTML_LOGS.PARSER_VERSION_ID;
    }

    @Override
    public Field<String> field5() {
        return HtmlLogs.HTML_LOGS.HTML;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return HtmlLogs.HTML_LOGS.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return HtmlLogs.HTML_LOGS.PARSED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getSiteId();
    }

    @Override
    public Integer component3() {
        return getSiteUriId();
    }

    @Override
    public Integer component4() {
        return getParserVersionId();
    }

    @Override
    public String component5() {
        return getHtml();
    }

    @Override
    public LocalDateTime component6() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component7() {
        return getParsed();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getSiteId();
    }

    @Override
    public Integer value3() {
        return getSiteUriId();
    }

    @Override
    public Integer value4() {
        return getParserVersionId();
    }

    @Override
    public String value5() {
        return getHtml();
    }

    @Override
    public LocalDateTime value6() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value7() {
        return getParsed();
    }

    @Override
    public HtmlLogsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public HtmlLogsRecord value2(Integer value) {
        setSiteId(value);
        return this;
    }

    @Override
    public HtmlLogsRecord value3(Integer value) {
        setSiteUriId(value);
        return this;
    }

    @Override
    public HtmlLogsRecord value4(Integer value) {
        setParserVersionId(value);
        return this;
    }

    @Override
    public HtmlLogsRecord value5(String value) {
        setHtml(value);
        return this;
    }

    @Override
    public HtmlLogsRecord value6(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public HtmlLogsRecord value7(LocalDateTime value) {
        setParsed(value);
        return this;
    }

    @Override
    public HtmlLogsRecord values(Long value1, Integer value2, Integer value3, Integer value4, String value5, LocalDateTime value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HtmlLogsRecord
     */
    public HtmlLogsRecord() {
        super(HtmlLogs.HTML_LOGS);
    }

    /**
     * Create a detached, initialised HtmlLogsRecord
     */
    public HtmlLogsRecord(Long id, Integer siteId, Integer siteUriId, Integer parserVersionId, String html, LocalDateTime createdAt, LocalDateTime parsed) {
        super(HtmlLogs.HTML_LOGS);

        set(0, id);
        set(1, siteId);
        set(2, siteUriId);
        set(3, parserVersionId);
        set(4, html);
        set(5, createdAt);
        set(6, parsed);
    }
}
